pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                bat 'C://Users//P102QBPH1//mvn//apache-maven-3.8.6//bin//mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                bat 'C://Users//P102QBPH1//mvn//apache-maven-3.8.6//bin//mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                bat './jenkins/scripts/deliver.sh'
            }
        }
    }
}
